# Generated by Django 4.1.7 on 2023-02-15 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default=datetime.datetime(2023, 2, 15, 15, 16, 35, 720005), max_length=1000),
        ),
    ]
